# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on

title: site
name: site name
description: site description
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
